config/routes.rb
Rails.application.routes.draw do
  
  root to: "pages#index"
  devise_for :users
  resources :movies
  get 'rents', to: 'movies#rents'
  get 'rent_a_movie', to: 'movies#make_a_rent'
  post 'rent_a_movie', to: 'movies#create_a_rent'
  get 'my_rents', to: 'rents#show_my_rents'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :rents, dependent: :restrict_with_error
  has_many :users, through: :rents

  scope :available, -> { where('stock > 0') }

  has_attached_file :poster, styles: { medium: "200x300#", thumb: "150x200" }
  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\z/
  
  validates_presence_of :name
  validates_presence_of :director
  validates_presence_of :synopsis
  validates_attachment_presence :poster

  validates :stock, :numericality => { :greater_than_or_equal_to => 0 }, :presence => true

end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rents
  has_many :movies, through: :rents
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :create_a_rent]
  before_action :authenticate_user!
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    if @movie.stock >= 10
      @text_class = 'success'
    elsif @movie.stock < 10 && @movie.stock > 5
      @text_class = 'warning'
    else
      @text_class = 'danger'
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_a_rent
    @available_movies = Movie.available
    respond_to do |format|
      format.js
    end
  end

  def create_a_rent
    ran = rand(1..100)
    if ran > 50
      @rent = Rent.new(user_id: current_user.id, movie_id: @movie.id, rent_date: Time.now)
      if @rent.save
        @movie.stock -= 1
        if @movie.save
          @message = '¡The rent is done!'
          @status = 201
        else
          @errors = @movie.errors
        end
      else
        @errors = @rent.errors
      end
    else
      @message = '¡You can not rent now because you have balance to pay'
      @status = 401
      respond_to do |format|
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :synopsis, :stock, :poster)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to '/movies' if user_signed_in?
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :authenticate_user!
  def show_my_rents
    @rents = Rent.where(user_id:current_user.id).group(:movie).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  </head>

  <body>
    <nav class='navbar navbar-default'>
      <div class='container'>
        <div class='navbar-header'>
          <% if user_signed_in? %>
          <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#auth-nav' aria-expanded='false'> 
            <span class='sr-only'>Toggle navigation</span> 
            <span class='icon-bar'></span> 
            <span class='icon-bar'></span> 
            <span class='icon-bar'></span>
          </button>
          <% end %>
          <%= link_to 'Movies App', root_path, class: 'navbar-brand' %>
        </div>
        <div class='navbar-collapse collapse' id='auth-nav' aria-expanded='false' style='height: 1px;'> 
        <% if user_signed_in? %>
          <p class='navbar-text navbar-right'>Welcome, <%= current_user.email %>!</p>        
          <p class='navbar-text navbar-right'><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>        
        <% end %>
        </div>
      </div>
    </nav>
    <main class='container'>
      <%= yield %>    
    </main>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <div class='row'>
    <div class='form-group col-md-6'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class='form-group col-md-6'>
      <%= f.label :director %>
      <%= f.text_field :director, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='form-group col-md-6'>
      <%= f.label :synopsis %>
      <%= f.text_field :synopsis, class: 'form-control' %>
    </div>
    <div class='form-group col-md-6'>
      <%= f.label :stock %>
      <%= f.number_field :stock, class: 'form-control' %>
    </div>
  </div>

  <div class='row'>
    <div class='form-group col-md-6'>
      <%= f.label :poster %> <br>
      <% if movie.poster.file? %>
        <%= image_tag movie.poster.url(:thumb) %>
      <% end %>      
      <%= f.file_field :poster %>
    </div>
  </div>

  <% if movie.errors.any? %>
    <div id='error_explanation' class='text-danger' role='alert'>
      <ul>
        <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='actions col-md-6 col-md-offset-3'>
      <%= f.submit 'Save movie', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', movies_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/movies/_rent_a_movie.html.erb
<div class='modal fade' id='rent_a_movie_modal' tabindex='-1' role='dialog' aria-labelledby='rent_a_movie_modalLabel'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
        <h4 class='modal-title' id='rent_a_movie_modalLabel'>Rent a Movie</h4>
      </div>
      <div class='modal-body'>
        
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-primary' data-dismiss='modal'>Done!</button>
      </div>
    </div>
  </div>
</div>

app/views/movies/_rent_response.html.erb
<div class='modal fade' id='rent_response_modal' tabindex='-1' role='dialog' aria-labelledby='rent_response_modalLabel'>
  <div class='modal-dialog modal-sm' role='document'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      </div>
      <div class='modal-body'>
        <h3 id='message'></h3>
      </div>
      <div class='modal-footer'>
        <button type='button' class='btn btn-primary' data-dismiss='modal'>Done!</button>
      </div>
    </div>
  </div>
</div>

app/views/movies/_rents.html.erb
<table class='table table-hover'>
<thead>
  <th class='text-center'>Name</th>
  <th class='text-center'>Available</th>
  <th colspan=1></th>
</thead>
<tbody>
<% @available_movies.each do |movie| %>
  <tr>
    <td class='text-center'>
      <%= movie.name %>
    </td>
    <td class='text-center'>
      <%= movie.stock %>
    </td>
    <td class='text-center'>
      <button class='btn btn-primary' onclick='rent_movie(<%= movie.id %>)'>Rent!</button>   
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/movies/create_a_rent.js.erb
let message_class = '';
if (<%= @status %> == <%= 201 %>){
  $('#rent_a_movie_modal').modal('hide');
  message_class = 'text-success';
}else{
  message_class = 'text-danger';
}
$('#rent_response_modal').find('.modal-body #message').attr('class',message_class);
$('#rent_response_modal').find('.modal-body #message').text('<%= @message %>');
$('#rent_response_modal').modal('show');

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<div class='btn-group' role='group' aria-label='...'>
  <button type='button' class='btn btn-default'><%= link_to 'New Movie', new_movie_path, class: 'link-unstyled' %></button>
  <button type='button' class='btn btn-default' data-toggle='modal' data-target='#rent_a_movie_modal'>Rent a Movie</button>
  <button type='button' class='btn btn-default'><%= link_to 'My Rents', my_rents_path, class: 'link-unstyled' %></button>
</div>
<table class='table text-center'>
  <thead>
    <tr>
      <th class='text-center'>Name</th>
      <th class='text-center hidden-xs'>Director</th>
      <th class='text-center visible-md visible-lg'>Stock</th>
      <th class='text-center' colspan='2'>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td class='hidden-xs'><%= movie.director %></td>
        <td class='visible-md visible-lg'><%= movie.stock %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <!--
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'rent_a_movie' %>
<%= render 'rent_response' %>

app/views/movies/make_a_rent.erb
$('#rent_a_movie_modal').find('.modal-body').html('<%= j render "rents" %>')

app/views/movies/make_a_rent.js.erb
let message_class = '';
if (<%= @status %> == 202){
  $('#rent_a_movie_modal').modal('hide');
  message_class = 'text-success';
}else{
  message_class = 'text-danger';
}
$('#rent_response_modal').find('.modal-body #message').attr('class',message_class);
$('#rent_response_modal').find('.modal-body #message').text('<%= @message %>');
$('#rent_response_modal').modal('show');

app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= render 'form', movie: @movie %>

app/views/movies/rents.js.erb
$('#rent_a_movie_modal').find('.modal-body').html('<%= j render "rents" %>')

app/views/movies/show.html.erb
<div class='row'>
  <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-0'>
    <h1><%= @movie.name %></h1>
    <p><strong>Director:</strong> <%= @movie.director %></p>
    <p class='text-<%= @text_class %>'><strong>Stock:</strong> There are <%= @movie.stock %> units available for rent.</p>    
    <p class='text-justify'><%= @movie.synopsis %><p>
  </div>
  <div class='col-xs-12 col-sm-12 col-md-4 text-center'>
    <%= image_tag @movie.poster.url(:medium) %>
  </div>
</div>
<div class='row'>
  <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-0'>
    <div class='actions btn-group' role='group' aria-label='...'>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary' %>
      <%= link_to 'Back', movies_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class='jumbotron'>
  <h1>Movies App</h1>
  <p>Welcome to the MoviesApp. Here you will be able to create, edit and rent movies. Be careful, If you owe money, you won't be able to do any rent.</p>
  <p>Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'register a new account', new_user_registration_path %> to continue.</p>
</div>

app/views/rents/show_my_rents.html.erb
<header>
  <h1>My rents</h1>
  <%= link_to 'Back', movies_path, class: 'btn btn-default' %>
</header>
<div class='row'>
  <% @rents.each do |rent| %>
    <% quantity = rent[1] %>
    <% rent = rent[0] %>
    <div class='col-xs-12 col-sm-6 col-md-3'>
      <div class='thumbnail'>
        <%= image_tag rent.poster.url(:medium) %>
        <div class='caption'>
          <h3 class='truncate'><%= link_to rent.name, rent, class: 'link-unstyled' %></h3>
          <details>
          <summary>Synopsis</summary>
          <%= rent.synopsis %>
          </details>
          <small><%= quantity %> unities rented</small> 
        </div>
      </div>
    </div>
  <% end %>
</div>